### ISSUE TITLE
Captions endpoint can result in WebVTT file.

### ISSUE THREAD

**Issue by rbozan** [Siriusmart/invidious-rs#18] opened 2023-10-25 17:44 UTC
According to the Invidious documentation it would return a WebVTT format whenever you provide a `label` to the following endpoint:

https://github.com/Siriusmart/invidious-rs/blob/c3407a7ac2913be67bb9309073547ee8dd96fe1a/src/traits/clients.rs#L174-L177

For example: https://vid.puffyan.us/api/v1/captions/Rnvoq6uQC4w?label=Dutch+(auto-generated)

However, because of the deserialization calling this function in this lib results in:
```
called `Result::unwrap()` on an `Err` value: ExpectedError("Cannot deserialize response: expected value at line 1 column 1")
```

So this lib does not take this into account it seems.

As a workaround you can do the following:

```rs
    let client = get_invidious_client(); // The invidious client of this lib
    let result = client
        .fetch(&format!(
            "{}/api/v1/captions/{caption_id}?label={label}&languageCode={language}",
            client.instance
        ))
        .await?;

```

However it has not been stated anywhere in this lib that this is the case.

**Comment by Siriusmart** [comment] 2023-10-25 20:15
Um so when I do `client.captions("VIDEO_ID", None)`, it returns something like this

```rs
Captions {
    captions: [Caption {
        label: "English (auto-generated)",
        language: "",
        url: "/api/v1/captions/FhhyqkbtaR4?label=English+%28auto-generated%29"
    }]
}
```

Which contains the url to the real captions file, I guess I'll just fix up some docs on how this works and bump up the crate.

**Comment by Siriusmart** [comment] 2023-10-25 20:29
But do u think its a bit overkill to bump up the version without any real changes?

**Comment by rbozan** [comment] 2023-10-25 20:39
If I was you I'd just bump up the patch version to 0.7.3 as you only changed the docs.

**Comment by Siriusmart** [comment] 2023-10-26 09:17
> ```rust
>     let client = get_invidious_client(); // The invidious client of this lib
>     let result = client
>         .fetch(&format!(
>             "{}/api/v1/captions/{caption_id}?label={label}&languageCode={language}",
>             client.instance
>         ))
>         .await?;
> ```

Given that `client.captions()` returns a url that looks like this `/api/v1/captions/FhhyqkbtaR4?label=English+%28auto-generated%29`, I have made some changes to the `client.fetch()` function.

- That string can just be passed into `client.fetch()`, without needing to use `format!("{instance}{url}")`
- The url can include leading slashed, or not
- The original behaviour of `client.fetch()` is a duplicate of `client.method.fetch()`, so if you still want the original behaviour, it's still there. But since `client` is already specific to an instance, it would make sense to not ask for the instance address again

(note: that piece of code will break on 0.7.3)

**Closed by Siriusmart** 2023-10-26 09:17 UTC
